/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import java.awt.Component;
import java.awt.Desktop;
import java.io.File;
import java.io.FileReader;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.regex.Pattern;
import javax.swing.JCheckBox;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import mapeamento.Funcionario;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import utilitario.Conectar;

/**
 *
 * @author Aline
 */
public class FormRelatorioAluno extends javax.swing.JFrame {

    /**
     * Creates new form FormRelatorioEstagio
     */
    Funcionario f;
    public FormRelatorioAluno(Funcionario f) {
        this.f = f;
        initComponents();
        capturarCampos();
        capturarFiltro();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupFiltro = new javax.swing.ButtonGroup();
        groupTipo = new javax.swing.ButtonGroup();
        groupCampos = new javax.swing.ButtonGroup();
        jFiles = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btVisualizar = new javax.swing.JButton();
        btsalvar = new javax.swing.JButton();
        painelFiltro = new javax.swing.JPanel();
        ckPendentes = new javax.swing.JCheckBox();
        ckReprovados = new javax.swing.JCheckBox();
        ckAprovados = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        radCompleto = new javax.swing.JRadioButton();
        radSimplificado = new javax.swing.JRadioButton();
        radPersonalizado = new javax.swing.JRadioButton();
        painelCampos = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        ckId = new javax.swing.JCheckBox();
        ckNome = new javax.swing.JCheckBox();
        ckCpf = new javax.swing.JCheckBox();
        ckRg = new javax.swing.JCheckBox();
        ckTelefone = new javax.swing.JCheckBox();
        ckDatanasc = new javax.swing.JCheckBox();
        ckSexo = new javax.swing.JCheckBox();
        ckTurma = new javax.swing.JCheckBox();
        ckSituacao = new javax.swing.JCheckBox();

        jFiles.setDialogTitle("");
        jFiles.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(54, 54, 54));

        jPanel3.setBackground(new java.awt.Color(2, 67, 63));

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(252, 209, 71));
        jLabel1.setText("RELATÓRIO DE ALUNOS");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(54, 54, 54));

        btVisualizar.setText("VISUALIZAR");
        btVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVisualizarActionPerformed(evt);
            }
        });

        btsalvar.setText("SALVAR PDF");
        btsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsalvarActionPerformed(evt);
            }
        });

        painelFiltro.setBackground(new java.awt.Color(54, 54, 54));
        painelFiltro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        painelFiltro.setPreferredSize(new java.awt.Dimension(330, 170));

        ckPendentes.setBackground(new java.awt.Color(54, 54, 54));
        ckPendentes.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        ckPendentes.setForeground(new java.awt.Color(255, 255, 255));
        ckPendentes.setSelected(true);
        ckPendentes.setText("Pendentes");
        ckPendentes.setName("Pendente"); // NOI18N

        ckReprovados.setBackground(new java.awt.Color(54, 54, 54));
        ckReprovados.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        ckReprovados.setForeground(new java.awt.Color(255, 255, 255));
        ckReprovados.setSelected(true);
        ckReprovados.setText("Reprovados");
        ckReprovados.setName("Reprovado"); // NOI18N

        ckAprovados.setBackground(new java.awt.Color(54, 54, 54));
        ckAprovados.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        ckAprovados.setForeground(new java.awt.Color(255, 255, 255));
        ckAprovados.setSelected(true);
        ckAprovados.setText("Aprovados");
        ckAprovados.setName("Aprovado"); // NOI18N

        jLabel8.setFont(new java.awt.Font("Courier New", 1, 22)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Filtro.:");

        javax.swing.GroupLayout painelFiltroLayout = new javax.swing.GroupLayout(painelFiltro);
        painelFiltro.setLayout(painelFiltroLayout);
        painelFiltroLayout.setHorizontalGroup(
            painelFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelFiltroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ckPendentes)
                    .addComponent(ckAprovados)
                    .addComponent(jLabel8)
                    .addComponent(ckReprovados))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        painelFiltroLayout.setVerticalGroup(
            painelFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelFiltroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(8, 8, 8)
                .addComponent(ckAprovados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckReprovados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckPendentes)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(54, 54, 54));
        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.setPreferredSize(new java.awt.Dimension(330, 170));

        jLabel11.setFont(new java.awt.Font("Courier New", 1, 22)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Tipo Relatório.:");

        radCompleto.setBackground(new java.awt.Color(54, 54, 54));
        groupTipo.add(radCompleto);
        radCompleto.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        radCompleto.setForeground(new java.awt.Color(255, 255, 255));
        radCompleto.setText("Completo");
        radCompleto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radCompletoItemStateChanged(evt);
            }
        });

        radSimplificado.setBackground(new java.awt.Color(54, 54, 54));
        groupTipo.add(radSimplificado);
        radSimplificado.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        radSimplificado.setForeground(new java.awt.Color(255, 255, 255));
        radSimplificado.setSelected(true);
        radSimplificado.setText("Simplificado");
        radSimplificado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radSimplificadoItemStateChanged(evt);
            }
        });

        radPersonalizado.setBackground(new java.awt.Color(54, 54, 54));
        groupTipo.add(radPersonalizado);
        radPersonalizado.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        radPersonalizado.setForeground(new java.awt.Color(255, 255, 255));
        radPersonalizado.setText("Personalisado");
        radPersonalizado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radPersonalizadoItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radCompleto)
                    .addComponent(jLabel11)
                    .addComponent(radSimplificado, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radPersonalizado, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radCompleto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radSimplificado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radPersonalizado)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        painelCampos.setBackground(new java.awt.Color(54, 54, 54));
        painelCampos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        painelCampos.setPreferredSize(new java.awt.Dimension(330, 170));

        jLabel12.setFont(new java.awt.Font("Courier New", 1, 22)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Campos.:");

        ckId.setBackground(new java.awt.Color(54, 54, 54));
        ckId.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N
        ckId.setForeground(new java.awt.Color(255, 255, 255));
        ckId.setSelected(true);
        ckId.setText("Id");
        ckId.setEnabled(false);
        ckId.setName("Aluno.id"); // NOI18N

        ckNome.setBackground(new java.awt.Color(54, 54, 54));
        ckNome.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N
        ckNome.setForeground(new java.awt.Color(255, 255, 255));
        ckNome.setSelected(true);
        ckNome.setText("Nome");
        ckNome.setEnabled(false);
        ckNome.setName("Aluno.nome"); // NOI18N

        ckCpf.setBackground(new java.awt.Color(54, 54, 54));
        ckCpf.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N
        ckCpf.setForeground(new java.awt.Color(255, 255, 255));
        ckCpf.setSelected(true);
        ckCpf.setText("CPF");
        ckCpf.setEnabled(false);
        ckCpf.setName("Aluno.cpf"); // NOI18N

        ckRg.setBackground(new java.awt.Color(54, 54, 54));
        ckRg.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N
        ckRg.setForeground(new java.awt.Color(255, 255, 255));
        ckRg.setText("RG");
        ckRg.setEnabled(false);
        ckRg.setName("Aluno.rg"); // NOI18N

        ckTelefone.setBackground(new java.awt.Color(54, 54, 54));
        ckTelefone.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N
        ckTelefone.setForeground(new java.awt.Color(255, 255, 255));
        ckTelefone.setText("Telefone");
        ckTelefone.setEnabled(false);
        ckTelefone.setName("Aluno.telefone"); // NOI18N

        ckDatanasc.setBackground(new java.awt.Color(54, 54, 54));
        ckDatanasc.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N
        ckDatanasc.setForeground(new java.awt.Color(255, 255, 255));
        ckDatanasc.setText("Data de Nascimento");
        ckDatanasc.setEnabled(false);
        ckDatanasc.setName("Aluno.datanasc"); // NOI18N

        ckSexo.setBackground(new java.awt.Color(54, 54, 54));
        ckSexo.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N
        ckSexo.setForeground(new java.awt.Color(255, 255, 255));
        ckSexo.setText("Sexo");
        ckSexo.setEnabled(false);
        ckSexo.setName("Aluno.sexo"); // NOI18N

        ckTurma.setBackground(new java.awt.Color(54, 54, 54));
        ckTurma.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N
        ckTurma.setForeground(new java.awt.Color(255, 255, 255));
        ckTurma.setSelected(true);
        ckTurma.setText("Turma");
        ckTurma.setEnabled(false);
        ckTurma.setName("Aluno.turma"); // NOI18N

        ckSituacao.setBackground(new java.awt.Color(54, 54, 54));
        ckSituacao.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N
        ckSituacao.setForeground(new java.awt.Color(255, 255, 255));
        ckSituacao.setSelected(true);
        ckSituacao.setText("Situação");
        ckSituacao.setEnabled(false);
        ckSituacao.setName("Estagio.situacao"); // NOI18N

        javax.swing.GroupLayout painelCamposLayout = new javax.swing.GroupLayout(painelCampos);
        painelCampos.setLayout(painelCamposLayout);
        painelCamposLayout.setHorizontalGroup(
            painelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCamposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelCamposLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(ckId)
                        .addGap(18, 18, 18)
                        .addComponent(ckNome)
                        .addGap(18, 18, 18)
                        .addComponent(ckCpf)
                        .addGap(18, 18, 18)
                        .addComponent(ckRg)
                        .addGap(18, 18, 18)
                        .addComponent(ckTelefone)
                        .addGap(18, 18, 18)
                        .addComponent(ckSexo))
                    .addGroup(painelCamposLayout.createSequentialGroup()
                        .addComponent(ckDatanasc)
                        .addGap(18, 18, 18)
                        .addComponent(ckTurma)
                        .addGap(18, 18, 18)
                        .addComponent(ckSituacao)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelCamposLayout.setVerticalGroup(
            painelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCamposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(ckId)
                    .addComponent(ckNome)
                    .addComponent(ckCpf)
                    .addComponent(ckRg)
                    .addComponent(ckTelefone)
                    .addComponent(ckSexo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckDatanasc)
                    .addComponent(ckTurma)
                    .addComponent(ckSituacao))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(btsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btVisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(painelCampos, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(painelFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(painelCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btVisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVisualizarActionPerformed
        String sql = "";
        String cc = capturarCampos();
        String cf = capturarFiltro();
        if(cc != null && cf != null){
            sql = cc + cf;
            JasperPrint jp = gerarRelatorio(sql);
            if(jp != null){
                visualizarRelatorio(jp);
            }
        }else if(cc != null){
            sql = null;
        }
    }//GEN-LAST:event_btVisualizarActionPerformed

    private void btsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsalvarActionPerformed
        String sql = "";
        String cc = capturarCampos();
        String cf = capturarFiltro();
        String path = null;
        if(cc != null && cf != null){
            sql = cc + cf;
            JasperPrint jp = gerarRelatorio(sql);
            if(jp != null){int returnVal = jFiles.showOpenDialog(this);
                if (returnVal == JFileChooser.APPROVE_OPTION) {
                    File file = jFiles.getSelectedFile();
                    try {
                      // What to do with the file, e.g. display it in a TextArea
                        path = file.getAbsolutePath();
                    } catch (Exception ex) {
                      System.out.println("problem accessing file"+file.getAbsolutePath());
                      path = null;
                    }
                } else {
                    System.out.println("File access cancelled by user.");
                    path = null;
                }
                
                salvarRelatorio(jp, path);
            }
        }else if(cc != null){
            sql = null;
        }
    }//GEN-LAST:event_btsalvarActionPerformed

    private void radCompletoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radCompletoItemStateChanged
        if(radCompleto.isSelected()){
            ckId.setSelected(true);
            ckNome.setSelected(true);
            ckCpf.setSelected(true);
            ckRg.setSelected(true);
            ckTelefone.setSelected(true);
            ckSexo.setSelected(true);
            ckDatanasc.setSelected(true);
            ckTurma.setSelected(true);
            ckSituacao.setSelected(true);
        }
    }//GEN-LAST:event_radCompletoItemStateChanged

    private void radSimplificadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radSimplificadoItemStateChanged
       if(radSimplificado.isSelected()){
            ckNome.setSelected(true);
            ckCpf.setSelected(true);
            ckRg.setSelected(false);
            ckTelefone.setSelected(false);
            ckSexo.setSelected(false);
            ckDatanasc.setSelected(false);
            ckTurma.setSelected(true);
            ckSituacao.setSelected(true);
        }
    }//GEN-LAST:event_radSimplificadoItemStateChanged

    private void radPersonalizadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radPersonalizadoItemStateChanged
        if(radPersonalizado.isSelected()){
            ckNome.setEnabled(true);
            ckCpf.setEnabled(true);
            ckRg.setEnabled(true);
            ckTelefone.setEnabled(true);
            ckSexo.setEnabled(true);
            ckDatanasc.setEnabled(true);
            ckTurma.setEnabled(true);
            ckSituacao.setEnabled(true);
        }else{
            ckNome.setEnabled(false);
            ckCpf.setEnabled(false);
            ckRg.setEnabled(false);
            ckTelefone.setEnabled(false);
            ckSexo.setEnabled(false);
            ckDatanasc.setEnabled(false);
            ckTurma.setEnabled(false);
            ckSituacao.setEnabled(false);
        }
    }//GEN-LAST:event_radPersonalizadoItemStateChanged
    
    private String capturarCampos(){
        String sqlParams = "select ";
        int cont = 0;
        for (Component c : painelCampos.getComponents()){
            if("class javax.swing.JCheckBox".equals(c.getClass().toString())){
                JCheckBox ck = (JCheckBox) c;
                if(ck.isSelected()){
                    sqlParams += ck.getName();
                    sqlParams += ", ";
                    cont++;
                }
                else{
                    String field = ck.getName();
                    String[] result = field.split(Pattern.quote("."));
                    sqlParams += "null as "+field.substring(result[0].length()+1, field.length());
                    sqlParams += ", ";
                }
            }
        }
        sqlParams = sqlParams.substring(0, sqlParams.length()-2);
        sqlParams += " from Aluno INNER JOIN Estagio ON Aluno.id = Estagio.aluno_fk ";
        System.out.println(sqlParams);
        if(cont > 0){
            return sqlParams;
        }else{
            return null;
        }
    }
    
    private String capturarFiltro(){
        String sqlParams = "where situacao = ";
        int cont = 0;
        for (Component c : painelFiltro.getComponents()){
            if("class javax.swing.JCheckBox".equals(c.getClass().toString())){
                JCheckBox ck = (JCheckBox) c;
                if(ck.isSelected()){
                    sqlParams += "'"+ck.getName()+"' ";
                    sqlParams += "or situacao = ";
                    cont++;
                }
            }
        }
        sqlParams = sqlParams.substring(0, sqlParams.length()-14);
        sqlParams += ";";
        System.out.println(sqlParams);
        if(cont > 0){
            return sqlParams;
        }else{
            return null;
        }
    }
    
    private JasperPrint gerarRelatorio(String sql){
        System.out.println(sql);
        try{
            Map param = new HashMap();
            param.put("nomeFuncionario", "Gabriel");
            Connection con = Conectar.getConectar();
            PreparedStatement stm = con.prepareStatement(sql);
            ResultSet res = stm.executeQuery();
            JRResultSetDataSource resRelat = new JRResultSetDataSource(res);
            param.put("jr", resRelat);
            JasperPrint jpPrint = JasperFillManager.fillReport("src/relatorios/relatorio_alunos.jasper", param, resRelat);
            return jpPrint;
        }catch(Exception ex){
             JOptionPane.showMessageDialog(null, "Erro ao gerar relatório;");
             System.out.println(ex);
             return null;
        }
    }
    
    private void visualizarRelatorio(JasperPrint jpPrint){
        try{
            JasperViewer jv = new JasperViewer(jpPrint, false);
            jv.setExtendedState(JasperViewer.MAXIMIZED_BOTH);
            jv.setVisible(true);
            jv.toFront();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Erro ao Visualizar relatório;");
            System.out.println(ex);
        }
    }
    
    private void salvarRelatorio(JasperPrint jpPrint, String path){
        try{
            Date data = new Date();
            SimpleDateFormat formatador = new SimpleDateFormat("dd-MM-yyyy");
            String dataStr = formatador.format( data );
            
            String name = path+"/relatorioAlunos"+dataStr+".pdf";
            
            JasperExportManager.exportReportToPdfFile(jpPrint, name);
            Runtime.getRuntime().exec("cmd /e start "+name);
            File file = new File(name);
            
            Desktop desktop = Desktop.getDesktop();
            desktop.open(file);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Erro ao Salvar relatório;");
            System.out.println(ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormRelatorioAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormRelatorioAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormRelatorioAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormRelatorioAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormRelatorioAluno(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btVisualizar;
    private javax.swing.JButton btsalvar;
    private javax.swing.JCheckBox ckAprovados;
    private javax.swing.JCheckBox ckCpf;
    private javax.swing.JCheckBox ckDatanasc;
    private javax.swing.JCheckBox ckId;
    private javax.swing.JCheckBox ckNome;
    private javax.swing.JCheckBox ckPendentes;
    private javax.swing.JCheckBox ckReprovados;
    private javax.swing.JCheckBox ckRg;
    private javax.swing.JCheckBox ckSexo;
    private javax.swing.JCheckBox ckSituacao;
    private javax.swing.JCheckBox ckTelefone;
    private javax.swing.JCheckBox ckTurma;
    private javax.swing.ButtonGroup groupCampos;
    private javax.swing.ButtonGroup groupFiltro;
    private javax.swing.ButtonGroup groupTipo;
    private javax.swing.JFileChooser jFiles;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel painelCampos;
    private javax.swing.JPanel painelFiltro;
    private javax.swing.JRadioButton radCompleto;
    private javax.swing.JRadioButton radPersonalizado;
    private javax.swing.JRadioButton radSimplificado;
    // End of variables declaration//GEN-END:variables
}
