/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import dao.AlunoDAO;
import dao.EstagioDAO;
import dao.FuncionarioEmpDAO;
import dao.ProfOrientDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import mapeamento.Aluno;
import mapeamento.Estagio;
import mapeamento.FuncionarioEmpresa;
import mapeamento.ProfOrient;
import utilitario.Aparencia;

/**
 *
 * @author Guilherme
 */
public class FormEstagio extends javax.swing.JFrame {

    /**
     * Creates new form FormEstagio
     */
    public FormEstagio() {
        initComponents();
        preencherCb();
        preencherTabela(null);
        Aparencia.temaPrincipal(this);
        hideColumns();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabEstagio = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCadId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btCadSalvar = new javax.swing.JButton();
        btCadAtualizar = new javax.swing.JButton();
        btCadCancelar = new javax.swing.JButton();
        cbAluno = new javax.swing.JComboBox();
        cbProfOrient = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        cbSupervisor = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        cbAlunoHide = new javax.swing.JComboBox<>();
        cbProfOrientHide = new javax.swing.JComboBox<>();
        cbSupervisorHide = new javax.swing.JComboBox<>();
        cbSituacao = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        txtListPesquisa = new javax.swing.JTextField();
        btListPesquisa = new javax.swing.JButton();
        btListLimpar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbListEstagio = new javax.swing.JTable();
        btListExcluir = new javax.swing.JButton();
        btListEditar = new javax.swing.JButton();
        btListNovo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        tabEstagio.setBackground(new java.awt.Color(255, 255, 255));
        tabEstagio.setForeground(new java.awt.Color(54, 54, 54));
        tabEstagio.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        tabEstagio.setPreferredSize(new java.awt.Dimension(700, 500));

        jPanel1.setBackground(new java.awt.Color(54, 54, 54));

        jPanel3.setBackground(new java.awt.Color(2, 67, 63));

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(252, 209, 71));
        jLabel1.setText("CADASTRAR ESTÁGIO");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(155, 155, 155))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(54, 54, 54));

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID.:");

        txtCadId.setEditable(false);
        txtCadId.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Courier New", 1, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Prof. Orientador.:");

        jLabel5.setFont(new java.awt.Font("Courier New", 1, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Aluno.:");

        btCadSalvar.setText("SALVAR");
        btCadSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadSalvarActionPerformed(evt);
            }
        });

        btCadAtualizar.setText("ATUALIZAR");
        btCadAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadAtualizarActionPerformed(evt);
            }
        });

        btCadCancelar.setText("CANCELAR");
        btCadCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadCancelarActionPerformed(evt);
            }
        });

        cbAluno.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        cbAluno.setPreferredSize(new java.awt.Dimension(78, 40));

        cbProfOrient.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Courier New", 1, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Situação.:");

        cbSupervisor.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Courier New", 1, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Supervisor.:");

        cbSituacao.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        cbSituacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Em Andamento", "Aprovado", "Reprovado" }));
        cbSituacao.setSelectedIndex(-1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(btCadSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139)
                .addComponent(btCadAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btCadCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(cbProfOrient, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGap(34, 34, 34)
                                    .addComponent(cbSupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGap(45, 45, 45)
                                    .addComponent(jLabel6))))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5))
                            .addGap(44, 44, 44)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(txtCadId, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cbSituacao, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                            .addComponent(cbAlunoHide, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(cbProfOrientHide, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(27, 27, 27)
                            .addComponent(cbSupervisorHide, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCadId, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbProfOrient, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbAlunoHide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbProfOrientHide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSupervisorHide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCadSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCadAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCadCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 482, Short.MAX_VALUE))
        );

        tabEstagio.addTab("Cadastro", jPanel1);

        jPanel5.setBackground(new java.awt.Color(2, 67, 63));

        txtListPesquisa.setFont(new java.awt.Font("Courier New", 1, 22)); // NOI18N
        txtListPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtListPesquisaKeyTyped(evt);
            }
        });

        btListPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/lupa32.png"))); // NOI18N
        btListPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListPesquisaActionPerformed(evt);
            }
        });

        btListLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/borracha32.png"))); // NOI18N
        btListLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListLimparActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Courier New", 1, 28)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(252, 209, 71));
        jLabel9.setText("Pesquisar.:");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtListPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btListPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btListLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(btListPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtListPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btListLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel6.setBackground(new java.awt.Color(54, 54, 54));

        tbListEstagio.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N
        tbListEstagio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "ALUNO", "SUPERVISOR", "PROF. ORIENTADOR", "EMPRESA", "SITUAÇÃO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbListEstagio.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbListEstagio);
        if (tbListEstagio.getColumnModel().getColumnCount() > 0) {
            tbListEstagio.getColumnModel().getColumn(0).setResizable(false);
            tbListEstagio.getColumnModel().getColumn(0).setPreferredWidth(15);
            tbListEstagio.getColumnModel().getColumn(1).setPreferredWidth(130);
            tbListEstagio.getColumnModel().getColumn(2).setResizable(false);
            tbListEstagio.getColumnModel().getColumn(2).setPreferredWidth(130);
            tbListEstagio.getColumnModel().getColumn(3).setResizable(false);
            tbListEstagio.getColumnModel().getColumn(3).setPreferredWidth(120);
            tbListEstagio.getColumnModel().getColumn(4).setPreferredWidth(100);
            tbListEstagio.getColumnModel().getColumn(5).setPreferredWidth(100);
        }

        btListExcluir.setText("EXCLUIR");
        btListExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListExcluirActionPerformed(evt);
            }
        });

        btListEditar.setText("EDITAR");
        btListEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListEditarActionPerformed(evt);
            }
        });

        btListNovo.setText("NOVO");
        btListNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListNovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(btListNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addComponent(btListEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136)
                .addComponent(btListExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 734, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btListExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btListEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btListNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabEstagio.addTab("Lista de Estagio", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabEstagio, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabEstagio, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btListNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListNovoActionPerformed
        txtCadId.setText("");
        cbSituacao.setSelectedIndex(-1);
        cbAluno.setSelectedIndex(-1);
        cbProfOrient.setSelectedIndex(-1);
        cbSupervisor.setSelectedIndex(-1);

        btCadAtualizar.setVisible(false);
        btCadSalvar.setVisible(true);

        tabEstagio.setSelectedIndex(0);
    }//GEN-LAST:event_btListNovoActionPerformed

    private void btListEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListEditarActionPerformed
        int opcao = tbListEstagio.getSelectedRow();

        if(opcao >= 0){
            txtCadId.setText(tbListEstagio.getValueAt(opcao, 0).toString());
            Aluno a = (Aluno) tbListEstagio.getValueAt(opcao, 1);
            FuncionarioEmpresa fe = (FuncionarioEmpresa) tbListEstagio.getValueAt(opcao, 2);
            ProfOrient po = (ProfOrient) tbListEstagio.getValueAt(opcao, 3);
            cbSituacao.setSelectedItem(tbListEstagio.getValueAt(opcao, 5).toString());

            cbAlunoHide.setSelectedItem(a.getNome());
            int index1 = cbAlunoHide.getSelectedIndex();
            cbAluno.setSelectedIndex(index1);

            cbSupervisorHide.setSelectedItem(fe.getNome());
            int index2 = cbSupervisorHide.getSelectedIndex();
            cbSupervisor.setSelectedIndex(index2);

            cbProfOrientHide.setSelectedItem(po.getNome());
            int index3 = cbProfOrientHide.getSelectedIndex();
            cbProfOrient.setSelectedIndex(index3);

            tabEstagio.setSelectedIndex(0);

            btCadAtualizar.setVisible(true);
            btCadSalvar.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(null, "Selecione uma linha para continuar!");
        }
    }//GEN-LAST:event_btListEditarActionPerformed

    private void btListExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListExcluirActionPerformed
        int opcao = tbListEstagio.getSelectedRow();

        if(opcao >= 0){
            Estagio est = new Estagio();
            est.setId(Integer.parseInt(tbListEstagio.getValueAt(opcao, 0).toString()));
            est.setAluno_fk((Aluno) tbListEstagio.getValueAt(opcao, 1));
            est.setFucionarioEmp_fk((FuncionarioEmpresa) tbListEstagio.getValueAt(opcao, 2));
            est.setProfOrient_fk((ProfOrient) tbListEstagio.getValueAt(opcao, 3));
            est.setSituacao(tbListEstagio.getValueAt(opcao, 5).toString());

            EstagioDAO estDAO = new EstagioDAO();
            estDAO.excluir(est);

            preencherTabela(null);

        }else{
            JOptionPane.showMessageDialog(null, "Selecione uma linha para continuar!");
        }
    }//GEN-LAST:event_btListExcluirActionPerformed

    private void btCadCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadCancelarActionPerformed
        txtCadId.setText("");
        cbSituacao.setSelectedIndex(-1);
        cbAluno.setSelectedIndex(-1);
        cbProfOrient.setSelectedIndex(-1);
        cbSupervisor.setSelectedIndex(-1);

        btCadAtualizar.setVisible(false);
        btCadSalvar.setVisible(true);

        tabEstagio.setSelectedIndex(1);
    }//GEN-LAST:event_btCadCancelarActionPerformed

    private void btCadAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadAtualizarActionPerformed
        Estagio est = new Estagio();
        est.setId(Integer.parseInt(txtCadId.getText()));
        est.setAluno_fk((Aluno)cbAluno.getSelectedItem());
        est.setFucionarioEmp_fk((FuncionarioEmpresa) cbSupervisor.getSelectedItem());
        est.setProfOrient_fk((ProfOrient) cbProfOrient.getSelectedItem());
        est.setSituacao((String) cbSituacao.getSelectedItem());

        EstagioDAO estDAO = new EstagioDAO();

        estDAO.atualizar(est);

        btCadAtualizar.setVisible(false);
        btCadSalvar.setVisible(true);

        preencherTabela(null);
        tabEstagio.setSelectedIndex(1);
        btCadCancelarActionPerformed(evt);
    }//GEN-LAST:event_btCadAtualizarActionPerformed

    private void btCadSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadSalvarActionPerformed
        Estagio est = new Estagio();

        est.setAluno_fk((Aluno)cbAluno.getSelectedItem());
        est.setFucionarioEmp_fk((FuncionarioEmpresa) cbSupervisor.getSelectedItem());
        est.setProfOrient_fk((ProfOrient) cbProfOrient.getSelectedItem());
        est.setSituacao((String) cbSituacao.getSelectedItem());

        EstagioDAO estDAO = new EstagioDAO();

        estDAO.cadastrar(est);

        preencherTabela(null);
        tabEstagio.setSelectedIndex(1);
        btCadCancelarActionPerformed(evt);
    }//GEN-LAST:event_btCadSalvarActionPerformed

    private void btListPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListPesquisaActionPerformed
        preencherTabela(txtListPesquisa.getText());
        txtListPesquisa.requestFocus();
    }//GEN-LAST:event_btListPesquisaActionPerformed

    private void btListLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListLimparActionPerformed
        preencherTabela(null);
        txtListPesquisa.setText("");
        txtListPesquisa.requestFocus();
    }//GEN-LAST:event_btListLimparActionPerformed

    private void txtListPesquisaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtListPesquisaKeyTyped
        preencherTabela(txtListPesquisa.getText());
    }//GEN-LAST:event_txtListPesquisaKeyTyped
    
    // Método para preencher a tabela deEstagios
    private void preencherTabela(String busca){
        EstagioDAO estDAO = new EstagioDAO();
        List<Estagio> listaEstagios = estDAO.listarTodos(busca);
        DefaultTableModel modeloTbEstagios = (DefaultTableModel) tbListEstagio.getModel();
        modeloTbEstagios.setRowCount(0);
        listaEstagios.forEach((est) -> {
            modeloTbEstagios.addRow(new Object[] {est.getId(), est.getAluno_fk(), est.getFucionarioEmp_fk(), est.getProfOrient_fk(), est.getFucionarioEmp_fk().getEmpresa_fk(), est.getSituacao()});
        });
    }
    
    private void preencherCb(){
        cbAlunoHide.setVisible(false);
        cbProfOrientHide.setVisible(false);
        cbSupervisorHide.setVisible(false);
        
        AlunoDAO aDAO = new AlunoDAO();
        List<Aluno> listaAlunos = aDAO.listarTodos(null);
        for(Aluno a: listaAlunos){
            cbAluno.addItem(a);
            cbAlunoHide.addItem(a.getNome());
        }
        
        ProfOrientDAO poDAO = new ProfOrientDAO();
        List<ProfOrient> listaProfOrients = poDAO.listarTodos(null);
        for(ProfOrient po: listaProfOrients){
            cbProfOrient.addItem(po);
            cbProfOrientHide.addItem(po.getNome());
        }
        
        FuncionarioEmpDAO feDAO = new FuncionarioEmpDAO();
        List<FuncionarioEmpresa> listaFuncionariosEmp = feDAO.listarSupervisores();
        for(FuncionarioEmpresa fe: listaFuncionariosEmp){
            cbSupervisor.addItem(fe);
            cbSupervisorHide.addItem(fe.getNome());
        }
        
        cbAluno.setSelectedIndex(-1);
        cbAlunoHide.setSelectedIndex(-1);
        cbProfOrient.setSelectedIndex(-1);
        cbProfOrientHide.setSelectedIndex(-1);
        cbSupervisor.setSelectedIndex(-1);
        cbSupervisorHide.setSelectedIndex(-1);
    }
    
    public void hideColumns(){
        tbListEstagio.getColumnModel().getColumn(2).setMinWidth(0);
        tbListEstagio.getColumnModel().getColumn(2).setMaxWidth(0);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormEstagio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadAtualizar;
    private javax.swing.JButton btCadCancelar;
    private javax.swing.JButton btCadSalvar;
    private javax.swing.JButton btListEditar;
    private javax.swing.JButton btListExcluir;
    private javax.swing.JButton btListLimpar;
    private javax.swing.JButton btListNovo;
    private javax.swing.JButton btListPesquisa;
    private javax.swing.JComboBox cbAluno;
    private javax.swing.JComboBox<String> cbAlunoHide;
    private javax.swing.JComboBox cbProfOrient;
    private javax.swing.JComboBox<String> cbProfOrientHide;
    private javax.swing.JComboBox<String> cbSituacao;
    private javax.swing.JComboBox cbSupervisor;
    private javax.swing.JComboBox<String> cbSupervisorHide;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane tabEstagio;
    private javax.swing.JTable tbListEstagio;
    private javax.swing.JTextField txtCadId;
    private javax.swing.JTextField txtListPesquisa;
    // End of variables declaration//GEN-END:variables
}
