/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import dao.FuncionarioDAO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import mapeamento.Funcionario;
import utilitario.Aparencia;
import utilitario.Validacoes;

/**
 *
 * @author Aline
 */
public class FormFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form FormFuncionario
     */
    public FormFuncionario() {
        initComponents();
        btCadAtualizar.setVisible(false);
        preencherTabela(null);
        Aparencia.temaPrincipal(this);
        hideColumns();
        txtCadId.setText("N/A");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupSexo = new javax.swing.ButtonGroup();
        jPanel7 = new javax.swing.JPanel();
        tabFuncionario = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCadId = new javax.swing.JTextField();
        txtCadNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCadCpf = new javax.swing.JFormattedTextField();
        txtCadtRg = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCadDataNasc = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        btCadSalvar = new javax.swing.JButton();
        btCadAtualizar = new javax.swing.JButton();
        btCadCancelar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtCadFormacao = new javax.swing.JTextField();
        txtCadSenha = new javax.swing.JPasswordField();
        ckExibirSenha = new javax.swing.JCheckBox();
        jPanel8 = new javax.swing.JPanel();
        radCadFeminino = new javax.swing.JRadioButton();
        radCadMasculino = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        txtListPesquisa = new javax.swing.JTextField();
        btListPesquisa = new javax.swing.JButton();
        btListLimpar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbListFuncionarios = new javax.swing.JTable();
        btListExcluir = new javax.swing.JButton();
        btListEditar = new javax.swing.JButton();
        btListNovo = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        tabFuncionario.setBackground(new java.awt.Color(255, 255, 255));
        tabFuncionario.setForeground(new java.awt.Color(54, 54, 54));
        tabFuncionario.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        tabFuncionario.setPreferredSize(new java.awt.Dimension(700, 500));

        jPanel1.setBackground(new java.awt.Color(54, 54, 54));

        jPanel3.setBackground(new java.awt.Color(2, 67, 63));

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(252, 209, 71));
        jLabel1.setText("CADASTRAR FUNCIONÁRIO");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(54, 54, 54));

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID.:");

        txtCadId.setEditable(false);
        txtCadId.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N

        txtCadNome.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Courier New", 1, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CPF.:");

        jLabel5.setFont(new java.awt.Font("Courier New", 1, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nome.:");

        jLabel4.setFont(new java.awt.Font("Courier New", 1, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Data Nascimento.:");

        jLabel6.setFont(new java.awt.Font("Courier New", 1, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Formação.:");

        try {
            txtCadCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCadCpf.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N

        txtCadtRg.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Courier New", 1, 22)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("RG.:");

        try {
            txtCadDataNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCadDataNasc.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Courier New", 1, 22)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Sexo.:");

        btCadSalvar.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        btCadSalvar.setText("SALVAR");
        btCadSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadSalvarActionPerformed(evt);
            }
        });

        btCadAtualizar.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        btCadAtualizar.setText("ATUALIZAR");
        btCadAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadAtualizarActionPerformed(evt);
            }
        });

        btCadCancelar.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        btCadCancelar.setText("CANCELAR");
        btCadCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadCancelarActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Courier New", 1, 22)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Senha.:");

        txtCadFormacao.setFont(new java.awt.Font("Courier New", 1, 22)); // NOI18N

        txtCadSenha.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N

        ckExibirSenha.setBackground(new java.awt.Color(54, 54, 54));
        ckExibirSenha.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        ckExibirSenha.setForeground(new java.awt.Color(255, 255, 255));
        ckExibirSenha.setText("Exibir Senha");
        ckExibirSenha.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ckExibirSenhaStateChanged(evt);
            }
        });

        jPanel8.setBackground(new java.awt.Color(54, 54, 54));

        radCadFeminino.setBackground(new java.awt.Color(54, 54, 54));
        groupSexo.add(radCadFeminino);
        radCadFeminino.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        radCadFeminino.setForeground(new java.awt.Color(255, 255, 255));
        radCadFeminino.setSelected(true);
        radCadFeminino.setText("Feminino");

        radCadMasculino.setBackground(new java.awt.Color(54, 54, 54));
        groupSexo.add(radCadMasculino);
        radCadMasculino.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        radCadMasculino.setForeground(new java.awt.Color(255, 255, 255));
        radCadMasculino.setText("Masculino");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(radCadFeminino, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(radCadMasculino, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(radCadFeminino)
                .addComponent(radCadMasculino))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(btCadSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btCadAtualizar)
                        .addGap(126, 126, 126)
                        .addComponent(btCadCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap(49, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCadNome, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCadId, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtCadCpf, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                                                .addComponent(txtCadtRg))
                                            .addGap(34, 34, 34)
                                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                                    .addComponent(jLabel4)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(txtCadDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel4Layout.createSequentialGroup()
                                                    .addComponent(jLabel6)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(txtCadFormacao))))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                            .addComponent(txtCadSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(41, 41, 41)
                                            .addComponent(ckExibirSenha)))
                                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(37, 37, 37))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCadId, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCadNome, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(38, 38, 38)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCadCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(txtCadDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCadtRg, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(txtCadFormacao, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtCadSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckExibirSenha))
                .addGap(53, 53, 53)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCadSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCadAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCadCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabFuncionario.addTab("Cadastro", jPanel1);

        jPanel5.setBackground(new java.awt.Color(2, 67, 63));

        txtListPesquisa.setFont(new java.awt.Font("Courier New", 1, 22)); // NOI18N
        txtListPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtListPesquisaKeyTyped(evt);
            }
        });

        btListPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/lupa32.png"))); // NOI18N
        btListPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListPesquisaActionPerformed(evt);
            }
        });

        btListLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/borracha32.png"))); // NOI18N
        btListLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListLimparActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Courier New", 1, 28)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(252, 209, 71));
        jLabel9.setText("Pesquisar.:");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtListPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btListPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btListLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(btListPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtListPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btListLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel6.setBackground(new java.awt.Color(54, 54, 54));

        tbListFuncionarios.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N
        tbListFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NOME", "CPF", "RG", "DATA NASC", "SEXO", "FORMACAO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbListFuncionarios);
        if (tbListFuncionarios.getColumnModel().getColumnCount() > 0) {
            tbListFuncionarios.getColumnModel().getColumn(0).setResizable(false);
            tbListFuncionarios.getColumnModel().getColumn(0).setPreferredWidth(15);
            tbListFuncionarios.getColumnModel().getColumn(1).setPreferredWidth(130);
            tbListFuncionarios.getColumnModel().getColumn(2).setResizable(false);
            tbListFuncionarios.getColumnModel().getColumn(2).setPreferredWidth(130);
            tbListFuncionarios.getColumnModel().getColumn(3).setResizable(false);
            tbListFuncionarios.getColumnModel().getColumn(4).setResizable(false);
            tbListFuncionarios.getColumnModel().getColumn(4).setPreferredWidth(100);
            tbListFuncionarios.getColumnModel().getColumn(5).setResizable(false);
            tbListFuncionarios.getColumnModel().getColumn(6).setPreferredWidth(100);
        }

        btListExcluir.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        btListExcluir.setText("EXCLUIR");
        btListExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListExcluirActionPerformed(evt);
            }
        });

        btListEditar.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        btListEditar.setText("EDITAR");
        btListEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListEditarActionPerformed(evt);
            }
        });

        btListNovo.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        btListNovo.setText("NOVO");
        btListNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListNovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(btListNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addComponent(btListEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136)
                .addComponent(btListExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 734, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btListExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btListEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btListNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabFuncionario.addTab("Lista de Funcionários", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btCadSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadSalvarActionPerformed
        
        Validacoes v = new Validacoes();
        ArrayList<JTextField> array = new ArrayList<>();
        txtCadCpf.setName("cpf");
        txtCadDataNasc.setName("data");
        array.add(txtCadNome);
        array.add(txtCadCpf);
        array.add(txtCadtRg);
        array.add(txtCadFormacao);
        array.add(txtCadDataNasc);
        array.add(txtCadSenha);
        
        String result = v.validarCampos(array);
        if(result.equals("valido")){
            String sexo = radCadFeminino.getText();
            Funcionario f = new Funcionario();
            f.setNome(txtCadNome.getText());
            f.setCpf(txtCadCpf.getText());
            f.setRg(txtCadtRg.getText());
            f.setFormacao(txtCadFormacao.getText());
            f.setDatanasc(txtCadDataNasc.getText());
            if(radCadFeminino.isSelected()){
                sexo = radCadFeminino.getText();
            }else if(radCadMasculino.isSelected()){
                sexo = radCadMasculino.getText();
            }
            f.setSexo(sexo);
            f.setSenha(txtCadSenha.getText());

            FuncionarioDAO fDAO = new FuncionarioDAO();

            fDAO.cadastrar(f);

            preencherTabela(null);
            tabFuncionario.setSelectedIndex(1);
            btCadCancelarActionPerformed(evt);
        }else{
            JOptionPane.showMessageDialog(null, result);
        }
    }//GEN-LAST:event_btCadSalvarActionPerformed

    private void btCadAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadAtualizarActionPerformed
        Validacoes v = new Validacoes();
        ArrayList<JTextField> array = new ArrayList<>();
        txtCadCpf.setName("cpf");
        txtCadDataNasc.setName("data");
        array.add(txtCadNome);
        array.add(txtCadCpf);
        array.add(txtCadtRg);
        array.add(txtCadFormacao);
        array.add(txtCadDataNasc);
        
        String result = v.validarCampos(array);
        if(result.equals("valido")){    
            String sexo = radCadFeminino.getText();
            Funcionario f = new Funcionario();
            f.setId_funcionario(Integer.parseInt(txtCadId.getText()));
            f.setNome(txtCadNome.getText());
            f.setCpf(txtCadCpf.getText());
            f.setRg(txtCadtRg.getText());
            f.setFormacao(txtCadFormacao.getText());
            f.setDatanasc(txtCadDataNasc.getText());
            if(radCadFeminino.isSelected()){
                sexo = radCadFeminino.getText();
            }else if(radCadMasculino.isSelected()){
                sexo = radCadMasculino.getText();
            }
            f.setSexo(sexo);
            f.setSenha(txtCadSenha.getText());

            FuncionarioDAO fDAO = new FuncionarioDAO();

            fDAO.atualizar(f);

            preencherTabela(null);

            txtCadSenha.setEditable(true);

            btCadAtualizar.setVisible(false);
            btCadSalvar.setVisible(true);

            tabFuncionario.setSelectedIndex(1);
            btCadCancelarActionPerformed(evt);
        }else{
            JOptionPane.showMessageDialog(null, result);
        }
    }//GEN-LAST:event_btCadAtualizarActionPerformed

    private void btCadCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadCancelarActionPerformed
        txtCadId.setText("N/A");
        txtCadNome.setText("");
        txtCadCpf.setText("");
        txtCadtRg.setText("");
        txtCadDataNasc.setText("");
        txtCadFormacao.setText("");
        txtCadSenha.setText("");
        radCadFeminino.setSelected(true);
        
        txtCadSenha.setEditable(true);

        btCadAtualizar.setVisible(false);
        btCadSalvar.setVisible(true);

        tabFuncionario.setSelectedIndex(1);
    }//GEN-LAST:event_btCadCancelarActionPerformed

    private void btListExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListExcluirActionPerformed
        int opcao = tbListFuncionarios.getSelectedRow();

        if(opcao >= 0){
            Funcionario f = new Funcionario();
            f.setId_funcionario(Integer.parseInt(tbListFuncionarios.getValueAt(opcao, 0).toString()));
            f.setNome(tbListFuncionarios.getValueAt(opcao, 1).toString());
            f.setCpf(tbListFuncionarios.getValueAt(opcao, 2).toString());
            f.setRg(tbListFuncionarios.getValueAt(opcao, 3).toString());
            f.setDatanasc(tbListFuncionarios.getValueAt(opcao, 4).toString());
            String sexo = tbListFuncionarios.getValueAt(opcao, 5).toString();
            f.setSexo(sexo);
            f.setFormacao(tbListFuncionarios.getValueAt(opcao, 6).toString());
            
            FuncionarioDAO fDAO = new FuncionarioDAO();
            fDAO.excluir(f);
            
            preencherTabela(null);
        }else{
            JOptionPane.showMessageDialog(null, "Selecione uma linha para continuar!");
        }
    }//GEN-LAST:event_btListExcluirActionPerformed

    private void btListEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListEditarActionPerformed
        int opcao = tbListFuncionarios.getSelectedRow();

        if(opcao >= 0){
            txtCadId.setText(tbListFuncionarios.getValueAt(opcao, 0).toString());
            txtCadNome.setText(tbListFuncionarios.getValueAt(opcao, 1).toString());
            txtCadCpf.setText(tbListFuncionarios.getValueAt(opcao, 2).toString());
            txtCadtRg.setText(tbListFuncionarios.getValueAt(opcao, 3).toString());
            txtCadDataNasc.setText(tbListFuncionarios.getValueAt(opcao, 4).toString());
            String sexo = tbListFuncionarios.getValueAt(opcao, 5).toString();
            if(sexo.equals(radCadFeminino.getText())){
                radCadFeminino.setSelected(true);
            }else if(sexo.equals(radCadMasculino.getText())){
                radCadMasculino.setSelected(true);
            }
            txtCadFormacao.setText(tbListFuncionarios.getValueAt(opcao, 6).toString());
            
            txtCadSenha.setEditable(false);
            
            tabFuncionario.setSelectedIndex(0);
            
            btCadAtualizar.setVisible(true);
            btCadSalvar.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(null, "Selecione uma linha para continuar!");
        }
    }//GEN-LAST:event_btListEditarActionPerformed

    private void btListNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListNovoActionPerformed
        txtCadId.setText("N/A");
        txtCadNome.setText("");
        txtCadCpf.setText("");
        txtCadtRg.setText("");
        txtCadDataNasc.setText("");
        txtCadFormacao.setText("");
        txtCadSenha.setText("");
        radCadFeminino.setSelected(true);

        btCadAtualizar.setVisible(false);
        btCadSalvar.setVisible(true);

        tabFuncionario.setSelectedIndex(0);
    }//GEN-LAST:event_btListNovoActionPerformed

    private void ckExibirSenhaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ckExibirSenhaStateChanged
        if(ckExibirSenha.isSelected()){
            txtCadSenha.setEchoChar('\u0000');
        }else{
            txtCadSenha.setEchoChar('*');
        }
    }//GEN-LAST:event_ckExibirSenhaStateChanged

    private void btListPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListPesquisaActionPerformed
        preencherTabela(txtListPesquisa.getText());
    }//GEN-LAST:event_btListPesquisaActionPerformed

    private void btListLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListLimparActionPerformed
        preencherTabela(null);
        txtListPesquisa.setText("");
    }//GEN-LAST:event_btListLimparActionPerformed

    private void txtListPesquisaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtListPesquisaKeyTyped
        preencherTabela(txtListPesquisa.getText());
    }//GEN-LAST:event_txtListPesquisaKeyTyped
    
    // Método para preencher a tabela de Alunos
    public void preencherTabela(String busca){
        FuncionarioDAO fDAO = new FuncionarioDAO();
        List<Funcionario> listaFuncionarios = fDAO.listarTodos(busca);
        DefaultTableModel modeloTbFuncionarios = (DefaultTableModel) tbListFuncionarios.getModel();
        modeloTbFuncionarios.setRowCount(0);
        listaFuncionarios.forEach((f) -> {
            modeloTbFuncionarios.addRow(new Object[] {f.getId_funcionario(), f.getNome(), f.getCpf(), f.getRg(), f.getDatanasc(), f.getSexo(), f.getFormacao()});
        });
    }
    
    public void hideColumns(){
        tbListFuncionarios.getColumnModel().getColumn(3).setMinWidth(0);
        tbListFuncionarios.getColumnModel().getColumn(3).setMaxWidth(0);
        tbListFuncionarios.getColumnModel().getColumn(5).setMinWidth(0);
        tbListFuncionarios.getColumnModel().getColumn(5).setMaxWidth(0);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadAtualizar;
    private javax.swing.JButton btCadCancelar;
    private javax.swing.JButton btCadSalvar;
    private javax.swing.JButton btListEditar;
    private javax.swing.JButton btListExcluir;
    private javax.swing.JButton btListLimpar;
    private javax.swing.JButton btListNovo;
    private javax.swing.JButton btListPesquisa;
    private javax.swing.JCheckBox ckExibirSenha;
    private javax.swing.ButtonGroup groupSexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radCadFeminino;
    private javax.swing.JRadioButton radCadMasculino;
    private javax.swing.JTabbedPane tabFuncionario;
    private javax.swing.JTable tbListFuncionarios;
    private javax.swing.JFormattedTextField txtCadCpf;
    private javax.swing.JFormattedTextField txtCadDataNasc;
    private javax.swing.JTextField txtCadFormacao;
    private javax.swing.JTextField txtCadId;
    private javax.swing.JTextField txtCadNome;
    private javax.swing.JPasswordField txtCadSenha;
    private javax.swing.JTextField txtCadtRg;
    private javax.swing.JTextField txtListPesquisa;
    // End of variables declaration//GEN-END:variables
}
